repos:
- repo: git@github.ibm.com:Whitewater/whitewater-detect-secrets
  rev: 0.13.1+ibm.64.dss
  hooks:
    -   id: detect-secrets # pragma: whitelist secret
        args: [--baseline, .secrets.baseline, --no-keyword-scan ]
