language: generic
cache:
  directories:
  - "$HOME/.cache"
sudo: required
services:
- docker
env:
  matrix:
  - DOCKER_COMPOSE_VERSION=1.21.1
  global:
    secure:"xSQHKAR5d02DKlgZokRulFIXYTJ1yo297pkjeIFriUAWfQOxnCOs8XmEqed2ZOMxS/QO+wz57dxQuirdbXqWwsmaRyzy/BMrhOrqGvAFXqEaQOGkoVFpN7EHqTwvHn50mXB9pp3y+Da+JdohTVYXTibljXt2j+JvCVh0/fg5xShqhPB6/F4WsW+HPBP611cbV/lk6jhpFnUIM7bSEtkCeHJcJPf6OLGyUEXS4Vj03/I9AHV8dflRu7fbUYyzxNjrOyeZJgH+uGxCLn+03C+c0pO+qdfn1IZWU3q2mKZqpwb3kc0gbp+2hsW6VNXjLGpJKSLS7eB+a8VyZVTi4njcKi+ywI+r4rvO11UGnz47mQnL8P0imgrPCmjMwOB8I4+Yw2/I+xzA7OOnLzh6gOQJTgJtEKvPSRwLad5bwsDYP92BDRLIx+MGbR9BG+6rK5uJz51hb0QSyxN7tPwwaMRCU130ppaDnL4f35fNQ8Yq6HOmBAxeq2e7YBkEk7LYslWY8KzbQfNGzO9KT8Z6GYpRxUjKGuJBUD3iy4BPVWJ4Tl0YR0MuJmJhjlSJTH0uys3pAw6q0Nn5dHbmjk3WzHcCQ0Nc4CkWVeK31GZeCjFANEWQHiFC1HeuePuUP4E0EPyd4Hox5uxIhbhYxuhKhoWpmTXtYUBPPWH95sGx/G+UJ50="

- mkdir -p $HOME/.cache
- sudo rm /usr/local/bin/docker-compose
- curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname
  -s`-`uname -m` > docker-compose
- chmod +x docker-compose
- sudo mv docker-compose /usr/local/bin
- docker --version
- docker-compose version
script:
- sh -c "! egrep  -ri '(LICENSE[D]?).*(IBM)' --exclude='*.tar.gz' --exclude='.travis.yml'
  --exclude-dir='licenses' --exclude=index.jsp --exclude=error.jsp --exclude-dir='dockerhub'
  ."
- chmod +x build.sh
- "./build.sh"
- sudo service postgresql stop
- while sudo lsof -Pi :5432 -sTCP:LISTEN -t; do sleep 1; done
- export LICENSE=accept
- docker-compose up -d
- "./test/suite.sh"
notifications:
  slack: ibm-cloud:LbtLkB6RShLAntBS4thdFlqY
