language: java

sudo: required

services:
  - docker

env:
  - DOCKER_COMPOSE_VERSION=1.8.1

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - docker --version
  - docker-compose version

script:
  - chmod +x build.sh
  - ./build.sh
  - docker-compose up -d
  - cd test/
  - ./wait-for-url.sh http://localhost:9070/DecisionRunner
  - ./wait-for-url.sh http://localhost:9090/DecisionService
  - ./wait-for-url.sh http://localhost:9060/decisioncenter
  - ./wait-for-url.sh http://localhost:9060/teamserver
  - ./wait-for-url.sh http://localhost:9080/res
  # - ./check-authentication.sh
