version: '2'
services:
  dbserver:
    image: $REPOSITORY/dbserver:$ODMVERSION
    build:
        context: ../
        dockerfile: ./${ODMDOCKERDIR}/databases/derby/Dockerfile
        args:
        - ODMDOCKERDIR=$ODMDOCKERDIR
    ports:
    - 1527:1527
    environment:
      - SAMPLE=true
   # Uncomment this line to persist your data. Note that on OSX you need to share this
   # current directory in the Preference menu -> File Sharing menu.
   #    volumes:
   #    - ./:/opt/db-derby-10.12.1.1-bin

  odm-decisionserverconsole:
    image: $REPOSITORY/$PREFIXIMAGE-decisionserverconsole:$ODMVERSION
    build:
      context: ../
      dockerfile: ./${ODMDOCKERDIR}/decisionserver/decisionserverconsole/Dockerfile
      args:
        - ODMDOCKERDIR=$ODMDOCKERDIR
        - DRIVER_URL=$DRIVER_URL_DERBY
    links:
    - dbserver
    depends_on:
    - dbserver
    ports:
    - 9080:9080
    - 1883:1883
   # environment:
   # - DBSERVER_NAME=dbserver

  odm-decisionrunner:
    image: $REPOSITORY/$PREFIXIMAGE-decisionrunner:$ODMVERSION
    build:
      context: ../
      dockerfile: ./${ODMDOCKERDIR}/decisionserver/decisionrunner/Dockerfile
      args:
        - ODMDOCKERDIR=$ODMDOCKERDIR
        - DRIVER_URL=$DRIVER_URL_DERBY
    links:
    - dbserver
    - odm-decisionserverconsole
    depends_on:
    - dbserver
    - odm-decisionserverconsole
    ports:
    - 9070:9080

  odm-decisionserverruntime:
    image: $REPOSITORY/$PREFIXIMAGE-decisionserverruntime:$ODMVERSION
    build:
      context: ../
      dockerfile: ./${ODMDOCKERDIR}/decisionserver/decisionserverruntime/Dockerfile
      args:
        - ODMDOCKERDIR=$ODMDOCKERDIR
        - DRIVER_URL=$DRIVER_URL_DERBY
    links:
    - dbserver
    - odm-decisionserverconsole
    depends_on:
    - dbserver
    - odm-decisionserverconsole
    ports:
    - 9090:9080
    - 9443

  odm-decisioncenter:
    image: $REPOSITORY/$PREFIXIMAGE-decisioncenter:$ODMVERSION
    build:
      context: ../
      dockerfile: ./${ODMDOCKERDIR}/decisioncenter/Dockerfile
      args:
        - ODMDOCKERDIR=$ODMDOCKERDIR
        - DRIVER_URL=$DRIVER_URL_DERBY
    links:
    - dbserver
    depends_on:
    - dbserver
    ports:
    - 9060:9060
