services:
  dbserver:
    image: $REPOSITORY/dbserver:$ODMVERSION
    build:
        context: ../
        dockerfile: ./${ODMDOCKERDIR}/databases/postgresql/Dockerfile
        args:
        - ODMDOCKERDIR=$ODMDOCKERDIR
        - ODMDBVERSION=$ODMDBVERSION
        - ODMVERSION=$ODMVERSION
        - CP4BAVERSION=$CP4BAVERSION
        - FROMDOCKERBUILD=$FROMDOCKERBUILD
        - FROMPOSTGRES=$FROMPOSTGRES
        - POSTGRESUID=$POSTGRESUID
    user: "$POSTGRESUID:$POSTGRESUID"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U odmusr -d odmdb"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
    - 5432:5432
    environment:
      - POSTGRES_USER=odmusr
      - POSTGRES_PASSWORD=odmpwd
      - POSTGRES_DB=odmdb
      - PGDATA=/var/lib/postgresql/data
#     - SAMPLE=true
# Uncomment this line to persist your data. Note that on OSX you need to share this
# current directory in the Preference menu -> File Sharing menu.
#    volumes:
#      - ./pgdata:/pgdata

  odm-decisionserverconsole:
    image: $REPOSITORY/$PREFIXIMAGE-decisionserverconsole:$ODMVERSION
    build:
      context: ../
      dockerfile: ./${ODMDOCKERDIR}/decisionserver/decisionserverconsole/Dockerfile
      args:
        - ODMDOCKERDIR=$ODMDOCKERDIR
        - ODMVERSION=$ODMVERSION
        - CP4BAVERSION=$CP4BAVERSION
        - FROMLIBERTY=$FROMLIBERTY
        - FROMDOCKERBUILD=$FROMDOCKERBUILD
        - FROMLIBERTYBUILD=$FROMLIBERTY
        - PACKAGELIST=$PACKAGELIST
    depends_on:
    - dbserver
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-k", "-f", "https://localhost:9443/res/login.jsf"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 50s
    ports:
    - 9080:9080
    - 1883:1883
    - 9843:9443

  odm-decisionrunner:
    image: $REPOSITORY/$PREFIXIMAGE-decisionrunner:$ODMVERSION
    build:
      context: ../
      dockerfile: ./${ODMDOCKERDIR}/decisionserver/decisionrunner/Dockerfile
      args:
        - ODMDOCKERDIR=$ODMDOCKERDIR
        - ODMVERSION=$ODMVERSION
        - CP4BAVERSION=$CP4BAVERSION
        - FROMLIBERTY=$FROMLIBERTY
        - FROMDOCKERBUILD=$FROMDOCKERBUILD
        - FROMLIBERTYBUILD=$FROMLIBERTY
        - PACKAGELIST=$PACKAGELIST
    depends_on:
      dbserver:
        condition: service_healthy
      odm-decisionserverconsole:
        condition: service_healthy
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-k", "-f", "https://localhost:9443/DecisionRunner"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 50s
    ports:
    - 9070:9080
    - 9743:9443

  odm-decisionserverruntime:
    image: $REPOSITORY/$PREFIXIMAGE-decisionserverruntime:$ODMVERSION
    build:
      context: ../
      dockerfile: ./${ODMDOCKERDIR}/decisionserver/decisionserverruntime/Dockerfile
      args:
        - ODMDOCKERDIR=$ODMDOCKERDIR
        - ODMVERSION=$ODMVERSION
        - CP4BAVERSION=$CP4BAVERSION
        - FROMLIBERTY=$FROMLIBERTY
        - FROMLIBERTYBUILD=$FROMLIBERTY
        - FROMDOCKERBUILD=$FROMDOCKERBUILD
        - PACKAGELIST=$PACKAGELIST
    environment:
      - DECISIONSERVERCONSOLE_NAME=odm-decisionserverconsole
    depends_on:
      dbserver:
        condition: service_healthy
      odm-decisionserverconsole:
        condition: service_healthy
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-k", "-f", "https://localhost:9443/DecisionService"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 50s
    ports:
    - 9090:9080
    - 9943:9443


  odm-decisioncenter:
    image: $REPOSITORY/$PREFIXIMAGE-decisioncenter:$ODMVERSION
    build:
      context: ../
      dockerfile: ./${ODMDOCKERDIR}/decisioncenter/Dockerfile
      args:
        - ODMDOCKERDIR=$ODMDOCKERDIR
        - ODMVERSION=$ODMVERSION
        - CP4BAVERSION=$CP4BAVERSION
        - FROMLIBERTY=$FROMLIBERTY
        - FROMDOCKERBUILD=$FROMDOCKERBUILD
        - FROMLIBERTYBUILD=$FROMLIBERTY
        - PACKAGELIST=$PACKAGELIST
    depends_on:
    - dbserver
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-k", "-f", "https://localhost:9453/decisioncenter/healthCheck"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 50s
    environment:
    - JVM_ARGS="-Xmx14000m"
    ports:
    - 9060:9060
    - 9643:9453
