version: '2'
services:
  # This following property is defined in the .env file. It's allow to customize your docker images.
  # ODMVERSION : The Operational Decision Management version
  # ODMDOCKERDIR : The Directory where this
  odm-standalone:
    image: $REPOSITORY/odm:$ODMVERSION
    mem_limit: 4G
    memswap_limit: 4G
    build:
      context: ../
      dockerfile: ./$ODMDOCKERDIR/standalone/Dockerfile
      args:
        - ODMDOCKERDIR=$ODMDOCKERDIR
        - ODMVERSION=$ODMVERSION
        - ODMDBVERSION=$ODMDBVERSION
        - FROMLIBERTY=$FROMLIBERTY
    user: "1001:0"
    environment:
    - SAMPLE=false
    - LICENSE=accept
    - RedirectHost=https://localhost:9453
    ports:
    - 9080:9060
    - 9453:9453
    # Uncomment this line to persist your data. Note that on OSX you need to share this
    # current directory in the Preference menu -> File Sharing menu.
    #    volumes:
    #    - ./h2data:/config/dbdata/
    volumes:
    - ${PWD}/ums/ums.xml:/config/auth/ums.xml
    - ${PWD}/standalone/config/featureManager.xml:/config/featureManager.xml
#    - ${PWD}/ums/logging.xml:/config/logging/logging.xml
    - ${PWD}/ums/standalone-jvm.options:/config/jvm.options
    - ${PWD}/ums/webSecurity.xml:/config/auth/webSecurity.xml
    - ${PWD}/ums/dc-application.xml:/config/decisioncenter_application.xml
    - ${PWD}/ums/dr-application.xml:/config/decisionrunner_application.xml
    - ${PWD}/ums/dsc-application.xml:/config/decisionserverconsole_application.xml
    - ${PWD}/ums/dsr-application.xml:/config/decisionserverruntime_application.xml
    - ${PWD}/ums/odmkeystore.jks:/config/resources/security/odmkeystore.jks
    - ${PWD}/ums/odmtruststore.jks:/config/resources/security/odmtruststore.jks
    - ${PWD}/ums/OdmOidcProviders.json:/config/apps/decisioncenter.war/WEB-INF/classes/OdmOidcProviders.json
