version: '2'
services:
  dbserver:
    image: postgres:9.5
    ports:
    - 5432:5432
    environment:
      - POSTGRES_DB=odmdb
      - POSTGRES_USER=odmusr
      - POSTGRES_PASSWORD=odmpwd
      - PGDATA=/pgdata
# Uncomment this line to persist your data. Note that on OSX you need to share this
# current directory in the Preference menu -> File Sharing menu.
#    volumes:
#      - ./pgdata:/pgdata

  odm-standalone:
    image: $REPOSITORY/odm:$ODMVERSION
    build:
      context: ../
      dockerfile: ./$ODMDOCKERDIR/standalone/Dockerfile
      args:
        - ODMDOCKERDIR=$ODMDOCKERDIR
        - ODMVERSION=$ODMVERSION
    environment:
      - DB_TYPE=postgres
      # DB_TYPE can be set to "postgres" or "h2". If it is set to "h2" or not set, the H2 embedded database is used.
      # DB_DRIVER_URL can be used optionally to override the driver that is used by default for PostgreSQL.
      - DB_NAME=odmdb
      - DB_USER=odmusr
      - DB_PASSWORD=odmpwd
      - DB_SERVER_NAME=dbserver
      # DB_PORT_NUMBER can be used to override the default port number that is 5432 for PostgreSQL.
    ports:
      - 9080:9060
