version: '3'
services:
  dbserver:
    image: $REPOSITORY/dbserver:$ODMVERSION
    build:
        context: ../
        dockerfile: ./${ODMDOCKERDIR}/databases/postgresql/Dockerfile
        args:
        - ODMDOCKERDIR=$ODMDOCKERDIR
        - ODMDBVERSION=$ODMDBVERSION
        - ODMVERSION=$ODMVERSION
        - CP4BAVERSION=$CP4BAVERSION
        - FROMDOCKERBUILD=$FROMDOCKERBUILD
        - FROMPOSTGRES=$FROMPOSTGRES
        - POSTGRESUID=$POSTGRESUID
    user: "$POSTGRESUID:$POSTGRESUID"
    ports:
    - 5432:5432
    environment:
      - POSTGRES_USER=odmusr
      - POSTGRES_PASSWORD=odmpwd
      - POSTGRES_DB=odmdb
      - PGDATA=/var/lib/postgresql/data
#     - SAMPLE=true
# Uncomment this line to persist your data. Note that on OSX you need to share this
# current directory in the Preference menu -> File Sharing menu.
#    volumes:
#      - ./pgdata:/pgdata

  odm-decisionserverconsole:
    image: $REPOSITORY/$PREFIXIMAGE-decisionserverconsole:$ODMVERSION
    build:
      context: ../
      dockerfile: ./${ODMDOCKERDIR}/decisionserver/decisionserverconsole/Dockerfile
      args:
        - ODMDOCKERDIR=$ODMDOCKERDIR
        - ODMVERSION=$ODMVERSION
        - CP4BAVERSION=$CP4BAVERSION
        - FROMLIBERTY=$FROMLIBERTY
        - FROMDOCKERBUILD=$FROMDOCKERBUILD
        - FROMLIBERTYBUILD=$FROMLIBERTY
    links:
    - dbserver
    depends_on:
    - dbserver
    environment:
    - ENABLE_TLS=true
    - OPENID_MODE=PKCE
    - OPENID_CONFIG=true
    - OPENID_SERVER_URL=https://login.microsoftonline.com/90df2ccb-9053-40b8-9518-cc8835f62f7f
    - OPENID_PROVIDER=azuread
    - OPENID_CLIENT_ID=ee3b4617-c283-4a37-bca0-d81569a911f2
    - OPENID_CLIENT_SECRET=JVc8Q~VFlRkZXCn5wlUFDzfWnwEmwLGV4CHieaEb
    - OPENID_ALLOWED_DOMAINS=login.microsoftonline.com
    ports:
    - 9080:9080
    - 1883:1883
    - 9843:9443
    volumes:
    - ${PWD}/azuread/openIdWebSecurity.xml:/config/auth/openIdWebSecurity.xml
    - ${PWD}/azuread/openIdParameters.properties:/config/auth/openIdParameters.properties
    - ${PWD}/azuread/webSecurity.xml:/config/auth/webSecurity.xml
#    - ${PWD}/testprivatecertvolume:/config/security/private-cert-volume
    - ${PWD}/testpubliccertvolume:/config/security/trusted-cert-volume

  odm-decisionrunner:
    image: $REPOSITORY/$PREFIXIMAGE-decisionrunner:$ODMVERSION
    build:
      context: ../
      dockerfile: ./${ODMDOCKERDIR}/decisionserver/decisionrunner/Dockerfile
      args:
        - ODMDOCKERDIR=$ODMDOCKERDIR
        - ODMVERSION=$ODMVERSION
        - CP4BAVERSION=$CP4BAVERSION
        - FROMLIBERTY=$FROMLIBERTY
        - FROMDOCKERBUILD=$FROMDOCKERBUILD
        - FROMLIBERTYBUILD=$FROMLIBERTY
    links:
    - dbserver
    - odm-decisionserverconsole
    depends_on:
    - dbserver
    - odm-decisionserverconsole
    ports:
    - 9070:9080
    - 9743:9443
    environment:
    - ENABLE_TLS=true
    - OPENID_CONFIG=true
    - OPENID_MODE=PKCE
    - OPENID_SERVER_URL=https://login.microsoftonline.com/90df2ccb-9053-40b8-9518-cc8835f62f7f
    - OPENID_PROVIDER=azuread
    - OPENID_CLIENT_ID=ee3b4617-c283-4a37-bca0-d81569a911f2
    - OPENID_CLIENT_SECRET=JVc8Q~VFlRkZXCn5wlUFDzfWnwEmwLGV4CHieaEb
    - OPENID_ALLOWED_DOMAINS=login.microsoftonline.com
    - RES_URL=https://odm-decisionserverconsole:9443/res
    volumes:
    - ${PWD}/azuread/openIdWebSecurity.xml:/config/auth/openIdWebSecurity.xml
    - ${PWD}/azuread/openIdParameters.properties:/config/auth/openIdParameters.properties
    - ${PWD}/azuread/webSecurity.xml:/config/auth/webSecurity.xml
    - ${PWD}/azuread/AzureADProvider.json:/config/auth/OdmOidcProviders.json
#    - ${PWD}/testprivatecertvolume:/config/security/private-cert-volume
    - ${PWD}/testpubliccertvolume:/config/security/trusted-cert-volume

  odm-decisionserverruntime:
    image: $REPOSITORY/$PREFIXIMAGE-decisionserverruntime:$ODMVERSION
    build:
      context: ../
      dockerfile: ./${ODMDOCKERDIR}/decisionserver/decisionserverruntime/Dockerfile
      args:
        - ODMDOCKERDIR=$ODMDOCKERDIR
        - ODMVERSION=$ODMVERSION
        - CP4BAVERSION=$CP4BAVERSION
        - FROMLIBERTY=$FROMLIBERTY
        - FROMLIBERTYBUILD=$FROMLIBERTY
        - FROMDOCKERBUILD=$FROMDOCKERBUILD
    environment:
    - DECISIONSERVERCONSOLE_NAME=odm-decisionserverconsole
    - ENABLE_TLS=true
    - OPENID_CONFIG=true
    - OPENID_MODE=PKCE
    - OPENID_SERVER_URL=https://login.microsoftonline.com/90df2ccb-9053-40b8-9518-cc8835f62f7f
    - OPENID_PROVIDER=azuread
    - OPENID_CLIENT_ID=ee3b4617-c283-4a37-bca0-d81569a911f2
    - OPENID_CLIENT_SECRET=JVc8Q~VFlRkZXCn5wlUFDzfWnwEmwLGV4CHieaEb
    - OPENID_ALLOWED_DOMAINS=login.microsoftonline.com
    links:
    - dbserver
    - odm-decisionserverconsole
    depends_on:
    - dbserver
    - odm-decisionserverconsole
    ports:
    - 9090:9080
    - 9943:9443
    volumes:
    - ${PWD}/azuread/openIdWebSecurity.xml:/config/auth/openIdWebSecurity.xml
    - ${PWD}/azuread/openIdParameters.properties:/config/auth/openIdParameters.properties
    - ${PWD}/azuread/webSecurity.xml:/config/auth/webSecurity.xml
    - ${PWD}/azuread/AzureADProvider.json:/config/auth/OdmOidcProviders.json
#    - ${PWD}/testprivatecertvolume:/config/security/private-cert-volume
    - ${PWD}/testpubliccertvolume:/config/security/trusted-cert-volume

  odm-decisioncenter:
    image: $REPOSITORY/$PREFIXIMAGE-decisioncenter:$ODMVERSION
    build:
      context: ../
      dockerfile: ./${ODMDOCKERDIR}/decisioncenter/Dockerfile
      args:
        - ODMDOCKERDIR=$ODMDOCKERDIR
        - ODMVERSION=$ODMVERSION
        - CP4BAVERSION=$CP4BAVERSION
        - FROMLIBERTY=$FROMLIBERTY
        - FROMDOCKERBUILD=$FROMDOCKERBUILD
        - FROMLIBERTYBUILD=$FROMLIBERTY
    links:
    - dbserver
    depends_on:
    - dbserver
    environment:
    - JVM_ARGS="-Xmx14000m"
    - ENABLE_TLS=true
    - OPENID_CONFIG=true
    - OPENID_MODE=PKCE
    - OPENID_SERVER_URL=https://login.microsoftonline.com/90df2ccb-9053-40b8-9518-cc8835f62f7f
    - OPENID_PROVIDER=azuread
    - OPENID_CLIENT_ID=ee3b4617-c283-4a37-bca0-d81569a911f2
    - OPENID_CLIENT_SECRET=JVc8Q~VFlRkZXCn5wlUFDzfWnwEmwLGV4CHieaEb
    - OPENID_ALLOWED_DOMAINS=login.microsoftonline.com
    ports:
    - 9060:9060
    - 9643:9453
    volumes:
    - ${PWD}/azuread/openIdWebSecurity.xml:/config/auth/openIdWebSecurity.xml
    - ${PWD}/azuread/openIdParameters.properties:/config/auth/openIdParameters.properties
    - ${PWD}/azuread/webSecurity.xml:/config/auth/webSecurity.xml
    - ${PWD}/azuread/AzureADProvider.json:/config/auth/OdmOidcProviders.json
#    - ${PWD}/testprivatecertvolume:/config/security/private-cert-volume
    - ${PWD}/testpubliccertvolume:/config/security/trusted-cert-volume
