version: '2'
services:
  dbserver:
    build:
        dockerfile: ./${ODMDOCKERDIR}/databases/postgresql/Dockerfile
    environment:
            POSTGRES_USER: odm
            POSTGRES_PASSWORD: odm
            POSTGRES_DB: odmdb
            PGDATA: /pgdata
    ports:
    - 5432:5432

  decisionserverconsole:
    build:
      args:
        - DRIVER_URL=$DRIVER_URL_POSTGRES
    
  decisionrunner:
    build:
      args:
        - DRIVER_URL=$DRIVER_URL_POSTGRES

  decisionserverruntime:
    build:
      args:
        - DRIVER_URL=$DRIVER_URL_POSTGRES

  decisioncenter:
    build:
      args:
        - DRIVER_URL=$DRIVER_URL_POSTGRES