version: '3'
services:
  dbserver:
    build:
        dockerfile: ./${ODMDOCKERDIR}/databases/mysql/Dockerfile
    environment:
      - MYSQL_ROOT_PASSWORD=odmpwd
      - MYSQL_DATABASE=odmdb
      - MYSQL_USER=odmusr
      - MYSQL_PASSWORD=odmpwd
    ports:
    - 3306:3306

  odm-decisionserverconsole:
    environment:
      - DB_TYPE=mysql
      # DB_TYPE could be set to "derby", "mysql" or "postgres". If it is not set, the PostgreSQL database is used by default.
      # DB_DRIVER_URL could be used optionally to override the driver that is used by default for a given database.

  odm-decisionrunner:
     environment:
      - DB_TYPE=mysql
      # DB_TYPE could be set to "derby", "mysql" or "postgres". If it is not set, the PostgreSQL database is used by default.
      # DB_DRIVER_URL could be used optionally to override the driver that is used by default for a given database.

  odm-decisionserverruntime:
     environment:
      - DB_TYPE=mysql
      # DB_TYPE could be set to "derby", "mysql" or "postgres". If it is not set, the PostgreSQL database is used by default.
      # DB_DRIVER_URL could be used optionally to override the driver that is used by default for a given database.

  odm-decisioncenter:
     environment:
      - DB_TYPE=mysql
      # DB_TYPE could be set to "derby", "mysql" or "postgres". If it is not set, the PostgreSQL database is used by default.
      # DB_DRIVER_URL could be used optionally to override the driver that is used by default for a given database.
