#!/bin/bash

if [ ! "$HTTP_PORT" ]
then
  echo "HTTP_PORT unset : set $1"
  export HTTP_PORT=$1
fi

if [ ! "$HTTPS_PORT" ]
then
  echo "HTTPS_PORT unset : set $2"
  export HTTPS_PORT=$2
fi

echo "HTTPS_PORT : $HTTPS_PORT"
echo "HTTP_PORT : $HTTP_PORT"

if [ ! "$ODM_CONTEXT_ROOT" ]
then
  echo "ODM_CONTEXT_ROOT unset : set blank"
  export ODM_CONTEXT_ROOT=""
fi

if [ ! "$ENABLED_CIPHERS" ]
then
  echo "ENABLED_CIPHERS unset : set TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384 TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256 TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 TLS_RSA_WITH_AES_256_GCM_SHA384 TLS_RSA_WITH_AES_128_GCM_SHA256 TLS_AES_256_GCM_SHA384 TLS_CHACHA20_POLY1305_SHA256 TLS_AES_128_GCM_SHA256"
  export ENABLED_CIPHERS="TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384 TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256 TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 TLS_RSA_WITH_AES_256_GCM_SHA384 TLS_RSA_WITH_AES_128_GCM_SHA256 TLS_AES_256_GCM_SHA384 TLS_CHACHA20_POLY1305_SHA256 TLS_AES_128_GCM_SHA256"
fi

if [ -s "$SCRIPT/init/container.env" ]
then
    set -o allexport
    source $SCRIPT/init/container.env
    set +o allexport
fi
