version: '3'
services:
  dbserver:
    image: hyc-odm-docker.artifactory.swg-devops.com/dbserver:8.10.5.1-arm64

    ports:
    - 5432:5432
    environment:
      - POSTGRES_USER=odmusr
      - POSTGRES_PASSWORD=odmpwd
      - POSTGRES_DB=odmdb
      - SAMPLE=true
      - PGDATA=/var/lib/postgresql/data/pgdata
 

  odm-decisionserverconsole:
    image: hyc-odm-docker.artifactory.swg-devops.com/odm-decisionserverconsole:8.10.5.1-arm64
    links:
    - dbserver
    depends_on:
    - dbserver
    ports:
    - 9080:9080
    - 1883:1883
    - 9843:9443

  odm-decisionrunner:
    image: hyc-odm-docker.artifactory.swg-devops.com/odm-decisionrunner:8.10.5.1-arm64
    links:
    - dbserver
    - odm-decisionserverconsole
    depends_on:
    - dbserver
    - odm-decisionserverconsole
    ports:
    - 9070:9080
    - 9743:9443

  odm-decisionserverruntime:
    image: hyc-odm-docker.artifactory.swg-devops.com/odm-decisionserverruntime:8.10.5.1-arm64
    environment:
      - DECISIONSERVERCONSOLE_NAME=odm-decisionserverconsole
    links:
    - dbserver
    - odm-decisionserverconsole
    depends_on:
    - dbserver
    - odm-decisionserverconsole
    ports:
    - 9090:9080
    - 9943:9443

  odm-decisioncenter:
    image: hyc-odm-docker.artifactory.swg-devops.com/odm-decisioncenter:8.10.5.1-arm64
    links:
    - dbserver
    depends_on:
    - dbserver
    environment:
    - JVM_ARGS="-Xmx14000m"
    ports:
    - 9060:9060
    - 9643:9453
