version: '3'
services:

  dbserver:
    image: $TARGETREGISTRY/dbserver:$TARGETTAG
    build:
      context: ./
      dockerfile: ./Dockerfile
      args:
        - SOURCEIMAGE=$SOURCEREGISTRY/dbserver:$SOURCETAG

  odm-decisionserverconsole:
    image: $TARGETREGISTRY/odm-decisionserverconsole:$TARGETTAG
    build:
      context: ./
      dockerfile: ./Dockerfile
      args:
        - SOURCEIMAGE=$SOURCEREGISTRY/odm-decisionserverconsole:$SOURCETAG

  odm-decisionrunner:
    image: $TARGETREGISTRY/odm-decisionrunner:$TARGETTAG
    build:
      context: ./
      dockerfile: ./Dockerfile
      args:
        - SOURCEIMAGE=$SOURCEREGISTRY/odm-decisionrunner:$SOURCETAG 

  odm-decisionserverruntime:
    image: $TARGETREGISTRY/odm-decisionserverruntime:$TARGETTAG
    build:
      context: ./
      dockerfile: ./Dockerfile
      args:
        - SOURCEIMAGE=$SOURCEREGISTRY/odm-decisionserverruntime:$SOURCETAG 

  odm-decisioncenter:
    image: $TARGETREGISTRY/odm-decisioncenter:$TARGETTAG
    build:
      context: ./
      dockerfile: ./Dockerfile
      args:
        - SOURCEIMAGE=$SOURCEREGISTRY/odm-decisioncenter:$SOURCETAG

   