version: '2'
services:
  # This following property is defined in the .env file. It's allow to customize your docker images.
  # ODMVERSION : The Operational Decision Management version
  # ODMDOCKERDIR : The Directory where this
  odm-standalone:
    image: ibmcom/odm:8.10
    mem_limit: 4G
    memswap_limit: 4G
    user: "1001:0"
    environment:
    - SAMPLE=true
    - LICENSE=accept
    ports:
    - 9080:9060
    - 9453:9453
    # Uncomment this line to persist your data. Note that on OSX you need to share this
    # current directory in the Preference menu -> File Sharing menu.
    volumes:
    - ./kafka_client_odm.properties:/config/baiemitterconfig/plugin-configuration.properties
    - ../certs/kafka/truststore.p12:/config/truststore.p12