name: Build and test
on: [push]
env:
  ODM_FILE_NAME: odm-for-docker.zip
  ODM_VERSION: 9.5.0.0

jobs:
  Build-And-Test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - name: Log into Docker
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin
      - run: sudo apt update
      - run: sudo apt full-upgrade
      - run: docker info
      # - run: sh -c "! egrep -ri '(LICENSE[D]?).*(IBM)' --exclude='*.tar.gz' --exclude=.travis.yml --exclude-dir=licenses --exclude=index.jsp --exclude-dir=.git --exclude-dir=.github --exclude=error.jsp --exclude-dir=dockerhub ."
      - run: bash build.sh
        env:
          ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
          ARTIFACTORY_USER: ${{ secrets.ARTIFACTORY_USER }}
          ODM_URL: ${{ secrets.ODM_URL }}
      - run: sudo docker compose up -d
      - run: sh test/suite.sh
      - name: Report Status by slack
        if: always()
        uses: ravsamhq/notify-slack-action@master
        with:
          status: ${{ job.status }}
          # notify_when: 'failure'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
 #     - name: Report Status by mail
 #       if: always()
 #       uses: dawidd6/action-send-mail@v3
 #       with:
          # Specify connection via URL (replaces server_address, server_port, secure,
          # username and password)
          #
          # Format:
          #
          #  * smtp://user:password@server:port
          #  * smtp+starttls://user:password@server:port
          # connection_url: ${{secrets.MAIL_CONNECTION}}
          # Required mail server address if not connection_url:
 #         server_address: mx0a-001b2d01.pphosted.com
          # Server port, default 25:
          # server_port: 465
          # Optional whether this connection use TLS (default is true if server_port is 465)
          # secure: true
          # Optional (recommended) mail server username:
          # username: ${{secrets.MAIL_USERNAME}}
          # Optional (recommended) mail server password:
          # password: ${{secrets.MAIL_PASSWORD}}
          # Required mail subject:
 #         subject: Github Actions job result for DecisionsDev/odm-ondocker
          # Required recipients' addresses:
#          to: decisioncncf@ibm.com
          # Required sender full name (address can be skipped):
 #         from: Luke Skywalker # <user@example.com>
          # Optional plain body:
  #        body: Build job of ${{github.repository}} completed with ${{ job.status }}
          # Optional recipient of the email response:
   #       reply_to: decisioncncf@ibm.com
          # Optional unsigned/invalid certificates allowance:
    #      ignore_cert: true
          # Optional converting Markdown to HTML (set content_type to text/html too):
          # convert_markdown: true
          # Optional attachments:
          # attachments: attachments.zip,git.diff,./dist/static/*.js
