name: Create release and add asset
on:
  push:
    tags:
      - 'v*'

jobs:
  create-release:
    name: Create release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Get version from tag
        run: |
          tag_name="${{ github.ref_name }}"
          echo "odm_version=${tag_name##*v}" >> $GITHUB_ENV
      - name: Create Release
        id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: ODM ${{ env.odm_version }} Release
          body: |
            - First Change
            - Second Change
          draft: true
          prerelease: false
    outputs:
      upload_url: ${{ steps.create-release.outputs.upload_url }}
  deliver-src-test-script:
    name: Deliver validate-odm-script.zip
    runs-on: ubuntu-latest
    needs: create-release
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Create zip file
        run: |
          cd contrib
          zip -r validate-odm-script validate-odm -x "validate-odm/images/*"
          cd -
      - name: Upload Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: contrib/validate-odm-script.zip
          asset_name: validate-odm-script.zip
          asset_content_type: application/zip
